version: '3.9'
services:
  db-service:
    image: mysql
    container_name: mysql-bookstore_db
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootuser
      MYSQL_DATABASE: bookstore_db
    ports:
      - 3306:3306

volumes:
  db_data:
